# This file is the main config file for your service.

service: serverless-file-handler
provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
  region: us-east-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::myBucket", "/*" ] ] }

custom:
  myBucket: myBucket

functions:
  serverless-file-handler:
    handler: handler.handler
    events:
      - s3: ${self:custom.myBucket}